### ISSUE TITLE
Tharsis and Harrier thrust and mass issues

### ISSUE THREAD

**Issue by peterhaneve** [post-kerbin-mining-corporation/CryoEngines#101]
The CE-60 "Tharsis" Liquid Hydrogen Engine, despite its awesome model, is unfortunately very useless. It has a higher mass (3.0t vs 2.25t), is larger, and has less thrust (360 kN vs 390 kN) than the CE-2X "Ulysses" Liquid Hydrogen Engine, for the same ISP, meaning that it is never the best choice for any vessel. This vessel accelerates to the left:

![image](https://user-images.githubusercontent.com/29011570/117761518-5318fc80-b1dc-11eb-87b4-22db71aacbb0.png)

Perhaps 360 kN was intended to be per nozzle? A 720 kN thrust would make the engine useful in some situations.

Likewise, the MU-11 "Harrier" Liquid Methane Engine is worse than the MU-421 "Eagle" Liquid Methane engine, as it is heavier (4.0t vs 3.0t), has a lower ISP (376s vs 382s), and less thrust (300 kN vs 420 kN). It might be smaller, but at that point I would just use compact mount on the Eagle - perhaps the masses are swapped? Again, this vessel accelerates to the left.

![image](https://user-images.githubusercontent.com/29011570/117761841-e94d2280-b1dc-11eb-8cf7-a2b19f21f848.png)

Versions used: KSP 1.11, CryoEngines 2.0.1.

**Comment by ChrisAdderley** [comment]
Hey, thanks for the input. Note though - don't test like that. You're testing atmospheric engine thrust and Isp using vacuum engines. This will give inaccurate comparisons.

> The CE-60 "Tharsis" Liquid Hydrogen Engine, despite its awesome model, is unfortunately very useless. It has a higher mass (3.0t vs 2.25t), is larger, and has less thrust (360 kN vs 390 kN) than the CE-2X "Ulysses" Liquid Hydrogen Engine, for the same ISP, meaning that it is never the best choice for any vessel. This vessel accelerates to the left:

The Ulysses has 10 seconds lower Isp (458s) than the Tharsis (468s). It also has an overall weighting more towards TWR than the other vacuum engines. 

> Likewise, the MU-11 "Harrier" Liquid Methane Engine is worse than the MU-421 "Eagle" Liquid Methane engine, as it is heavier (4.0t vs 3.0t), has a lower ISP (376s vs 382s), and less thrust (300 kN vs 420 kN). It might be smaller, but at that point I would just use compact mount on the Eagle - perhaps the masses are swapped? Again, this vessel accelerates to the left.

Yes looks like that's right, it should be the other way around for masses according to my spreadsheet. I'll make sure this is adjusted for the next release.

**Comment by ChrisAdderley** [comment]
Released
