### ISSUE TITLE
Undefined useGimbalResponseSpeed field inside gimbal module

### ISSUE THREAD

**Issue by ValiZockt** [post-kerbin-mining-corporation/CryoEngines#102]
As per KSP API (see [here](https://www.kerbalspaceprogram.com/api/class_module_gimbal.html#ace3ecf394cd1008fb264e0af957f3fc0)) `useGimbalResponseSpeed` defaults to false, if not defined in the modules config node. In some configs this field is missing despite `gimbalResponseSpeed` being defined. 

Example from the [Buzzard Methalox Engine](https://github.com/post-kerbin-mining-corporation/CryoEngines/blob/master/GameData/CryoEngines/Parts/MethaloxEngines/125/cryoengine-buzzard-1.cfg#L157-L163)

```
MODULE	
{		
   name = ModuleGimbal		
   gimbalTransformName = B_Gimbal_M10		
   gimbalResponseSpeed = 7		
   gimbalRange = 3.5	
}
```

Just logging this here, if it wasn't intentional.

**Comment by ChrisAdderley** [comment]
By 'some' you must mean 'all ;)

**Comment by ChrisAdderley** [comment]
Released
