### ISSUE TITLE
CR-68 Shroud

### ISSUE THREAD

**Issue by ntrepid8** [post-kerbin-mining-corporation/CryoEngines#88]
It seems like sometimes the CR-68 Shroud stays attached to the engine after stage separation. I've tried disabling the shroud in the VAB or just using an engine plate but the behavior seems the same either way. Here is an example before stage separation:

![Kerbal Space Program_318](https://user-images.githubusercontent.com/482948/103663452-18a60700-4f3f-11eb-8ba7-856ab63c7e19.png)

And here is the same example after staging:

![Kerbal Space Program_319](https://user-images.githubusercontent.com/482948/103663503-29ef1380-4f3f-11eb-90d8-26d688242d1f.png)

A shroud pulls away with the separator but another shroud remains around the engine. Is this expected or should the should pull away from the engine like it does with the other engines?

Also, thanks for all your terrific mods! It seems like you've put a ton of work into these mods and it feels like the game is not complete without them.

**Comment by VabienArt** [comment]
Figured I'd put in my input and say I'm having a similar issue. I'm gonna take a look at the code but I doubt I'll find anything glaring.

**Comment by ChrisAdderley** [comment]
This should be fixed in the latest releases version

**Comment by ntrepid8** [comment]
Yup, it works correctly for me now. Thanks again for all the excellent mods!
