### ISSUE TITLE
Tanks missing LH2/Ox configurations

### ISSUE THREAD

**Issue by Machine-Maker** [post-kerbin-mining-corporation/CryoEngines#94]
Stock tank has HydraLox listed as a configuration but...
![image](https://user-images.githubusercontent.com/15055071/108754638-0be36f80-74fb-11eb-9e98-acc10645e48d.png)
It doesn't show up when I grab the part and try to change it.
![image](https://user-images.githubusercontent.com/15055071/108754715-23225d00-74fb-11eb-9709-24530588a278.png)

Also, the tank from cryotanks seems to be missing that configuration as well? Unless I'm missing something.
![image](https://user-images.githubusercontent.com/15055071/108754757-35040000-74fb-11eb-9575-a20d7fc04484.png)

**Comment by ChrisAdderley** [comment]
This mod doesn't supply configs for any of those resources, it's Interstellar Fuel Switch you should report this to.
