### ISSUE TITLE
Methalox balance feedback

### ISSUE THREAD

**Issue by LouisB3** [post-kerbin-mining-corporation/CryoEngines#95]
Some hopefully useful feedback on the prerelease methalox engines... 

Disclaimer: while some of this is based on my limited time spent building actual methalox launch vehicles, most of it comes from [comparing](https://www.dropbox.com/s/y3r5h021uioh34h/engine%20balance.xlsx?dl=0) different classes of engines from NFLV and CryoEngines and looking for outliers. I divided engines up based on fuel (LF/LCH4/LH2) and role (lower/upper) then compared them based on TWR, Isp, and cost/thrust in their primary environment (i.e., sea level or vacuum).

- The Hawk has poor TWR and the highest cost/thrust of any non-nuclear engine. To some extent I imagine this is because tiny engines are supposed to have compromised performance in some area (as with the Stromboli), but the cost could be reduced (inasmuch as small engine costs matter at all in KSP 😛 )
- The Deinonychus has the lowest cost/thrust of any (non-solid) engine in the game, by a fairly significant margin.
- The Buzzard has mediocre Isp (and typical performance otherwise) compared to other methalox upper engines; indeed, it's only somewhat better than typical LFO upper engines (or methalox lower engines).
- The Iguanodon has the highest TWR of any (non-solid) engine in the game, besting even quasi-OP yardsticks like the Twin-Boar and Manatee.
- The Harrier has relatively poor TWR (and ok performance otherwise) for a methalox upper engine.

**Comment by ChrisAdderley** [comment]
Thanks for the notes, I actually haven't tuned cost at all (if you look closely you can see that the configs were directly copied from similar LH2 engines). I will take those into account, and yeah definitely a typo (mass 3 vs 4) with the Iguanodon thrust.
